server:
  port: 9091
spring:
  application:
    name: zrq-spc-model
  cloud:
    nacos:
      discovery:
        server-addr: common-nacos-dev.magestack.cn:8848
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/zrq_spc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zrqspc?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
#    username: postgres
    password: zrq123
  data:
    redis:
      database: 2
      host: 192.168.101.128
      port: 6379
      password: zrq123
rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: zrq-spc-mock-excel-producer-group
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl-job:
  access-token: default_token
  admin:
    addresses: http://localhost:8088/xxl-job-admin
  executor:
    application-name: zrq-spc-learn-executor
    ip: 127.0.0.1
    log-retention-days: 3
    port: 19999