server:
  port: 9000
spring:
  application:
    name: zrq-spc-gateway
  data:
    redis:
      database: 2
      host: 192.168.101.128
      port: 6379
      password: zrq123
  cloud:
    nacos:
      discovery:
        server-addr: common-nacos-dev.magestack.cn:8848
    gateway:
      routes:
        - id: zrq-spc-gateway-route1
          uri: lb://zrq-spc-model
          predicates:
            - Path=/api/spc/model/user/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/spc/model/user/login
                  - /api/spc/model/user/register