---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2025/9/13 10:43
--- 这里combine方法必须写在最开始，redis加载lua脚本是按照顺序进行加载的，不会进行预解析
local function combine(firstValue, secondValue)
    firstValue = firstValue and 1 or 0;
    return (firstValue * 2 ^ 13) + secondValue;
end

local couponKey = KEYS[1];
local userListKey = KEYS[2];
local userInfo = ARGV[1];

local stock = tonumber(redis.call("HGET", couponKey, "couponStock"));

if stock == nil or stock <= 0 then
    local userListLength = redis.call("LLEN", userListKey);
    return combine(false, userListLength);
end

redis.call("HINCRBY", couponKey, "couponStock", -1);
redis.call("LPUSH", userListKey, userInfo);
local userListLength = redis.call("LLEN", userListKey);

return combine(true, userListLength);

