---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2025/11/19 21:18
---

local receiveUserKey = KEYS[1];
local limitKey = KEYS[2];
local couponId = ARGV[1];

redis.call("DEL", limitKey);
redis.call("ZREM", receiveUserKey, couponId);