---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2025/9/13 10:43
---

-- 返回失败列表
local failList = {}

-- 遍历所有 key
for i, key in ipairs(KEYS) do
    local value = ARGV[(i - 1) * 2 + 1]   -- value
    local expireAt = tonumber(ARGV[(i - 1) * 2 + 2])  -- 过期时间戳

    -- 如果 key 已经存在，说明用户已领取
    if redis.call("EXISTS", key) == 1 then
        table.insert(failList, key)
    else
        -- 不存在则写入 value
        redis.call("SET", key, value)
        if expireAt ~= nil and expireAt > 0 then
            redis.call("PEXPIREAT", key, expireAt) -- 绝对时间
            -- redis.call("PEXPIRE", key, expireAt) -- 相对时间(毫秒)
        end
    end
end

return failList

