---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2025/11/15 19:45
---
local prefix_limit_key = KEYS[1]
local coupon_receive_key = KEYS[2]
local coupon_id = KEYS[3]
local userIds = cjson.decode(ARGV[1])
local now = tonumber(ARGV[2])
local endTime = tonumber(ARGV[3])

for _, user_id in ipairs(userIds) do
    local key = coupon_receive_key .. user_id
    redis.call("ZADD", key, now, coupon_id);
    local limit_key = prefix_limit_key .. user_id .. "_" .. coupon_id;
    redis.call("INCR", limit_key)
    redis.call("EXPIRE", limit_key, endTime)
end