---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2025/11/24 16:09
--- 判断两个集合是否被删除，被删除就新建，没被删除就将原来的值更新
local limitKey = KEYS[1];
local receiveKey = KEYS[2];
local userId = ARGV[1];
local couponId = ARGV[2];
local now = ARGV[3];

local limitValue = redis.call("GET", limitKey);
local receiveValue = redis.call("ZSCORE", receiveKey, couponId);
--这里只有两种情况，要么这两个队列都有元素，要么都没有，这里的一致性应该由上游保证
if limitValue == nil and receiveValue == nil then
    --    代表被删除了
    redis.call("ADD", limitKey, 1);
    redis.call("ZADD", receiveKey, now, couponId);
else
    redis.call("INCR",limitKey);
    redis.call("ZADD", receiveKey, now, couponId);
end