---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2025/11/23 21:49
---
local limitKey = KEYS[1];
local receiveKey = KEYS[2];
local userId = tonumber(ARGV[1]);
local couponId = tonumber(ARGV[2]);

local receive_number = tonumber(redis.call("GET", limitKey));
if receive_number >= 1 then
    receive_number = receive_number - 1;
    if receive_number == 0 then
        redis.call("DEL", limitKey);
    else
        redis.call("INCRBY", limitKey, -1);
    end
else
    return -1;
end

local score = tonumber(redis.call("ZSCORE", receiveKey, couponId));
if score == nil then
    return -2;
else
    if receive_number == 0 then
        redis.call("ZREM", receiveKey, couponId);
    end
end